POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json

{

  "name": "amie",
  "lastname": "bah",
  "email": "jj@gmail.com",
  "password": "1294"
  
  
  
}

 
###
POST   http://localhost:3001/api/division HTTP/1.1
content-type: application/json

{
  "name": "BRIKAMA FC",
  "number": "FirstDivision",
  "userId": "63948843c636fa30ad00af59"
  
}

