# # PUT http://localhost:3001/api/user/6378e20e9733c2a97bf12dcf
# # content-type: application/json


# {
#   "email": "ac@camariana.gm",
#   "firstname": "A",
#   "minit": "",
#   "lastname": "Camara",
#   "role": "Admin"
# }

PUT  http://localhost:3001/api/division/6379854a8551a2683fe79eae
content-type: application/json

{
  "name": "realde bjl",
  "number": "2",
  "userId": "637983d66626c57162488a3f"
  
}