PUT http://localhost:3001/api/user/639473a7f93f25b8d44b0ac9
 content-type: application/json


 {
  "email": "ac@sal.gm",
  "firstname": "Alice",
  "minit": "",
  "lastname": "Mendy",
  "role": "Register"
 }

#PUT  http://localhost:3001/api/division/6379854a8551a2683fe79eae
#